# Generated by Django 4.1.7 on 2023-11-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seekers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('education', models.TextField()),
                ('work_experience', models.TextField()),
                ('skills', models.TextField()),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('github_profile', models.URLField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
