# Generated by Django 4.1.7 on 2023-11-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekers',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
