# Generated by Django 4.1.7 on 2023-10-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='stuname',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='stuid',
        ),
        migrations.AddField(
            model_name='job',
            name='companyname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.EmailField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='joblocation',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='jobtitle',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='jobtype',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='linkedin',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
