# Generated by Django 4.1.7 on 2023-10-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_rename_stuname_job_experience_remove_job_stuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='joblocation',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='jobtitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='jobtype',
            new_name='type',
        ),
    ]
