# Generated by Django 4.1.7 on 2023-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0003_rename_joblocation_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='companyname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
