# Generated by Django 4.1.7 on 2023-10-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0004_alter_job_companyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='companyname',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='job',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
        migrations.AddField(
            model_name='job',
            name='jobid',
            field=models.IntegerField(default='5'),
        ),
    ]
