# Generated by Django 4.1.7 on 2023-11-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0006_remove_job_jobid_job_companyname_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='companyname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='joblocation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobtitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobtype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='linkedin',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.CharField(max_length=30),
        ),
    ]
